### PR TITLE
(fix): Added a logrotate function to the crowdsec.go installer file

### LINKED ISSUE #2644: access.log eating disk space
### Describe the Bug

After some months of use my access.log is already > 3G. I think traefik config should set size limits and also enable compression

### Environment

- OS Type & Version: (e.g., Ubuntu 22.04)
- Pangolin Version: latest
- Gerbil Version: latest
- Traefik Version: latest
- Newt Version: latest
- Olm Version: (if applicable)

### To Reproduce

Just run it 

### Expected Behavior

Logs are limited in size and compressed (and rotated)

### PR DESCRIPTION
**Pull request by sidd190**
# Add logrotate config for Traefik access logs when CrowdSec is installed

Fixes #2644

**Documentation Update :** https://github.com/fosrl/docs-v2/pull/98

## What and why

The default Pangolin install does not enable Traefik access logging.  
When **CrowdSec** is selected during installation, the installer enables Traefik access logs (required for CrowdSec to detect threats).  

These logs are written to:  
`config/traefik/logs/access.log` (on the host)

Without log rotation, this file grows indefinitely, which is the issue reported in #2644.

This change fixes the problem **only** in the CrowdSec installation path, keeping the default install unaffected.

## What changed

**File modified:** `install/crowdsec.go`

- Added a new function: `setupTraefikLogRotate()`
- This function is called from `installCrowdsec()` immediately after the directory `config/traefik/logs/` is created.
- The function writes a logrotate configuration file to `/etc/logrotate.d/pangolin-traefik` using the absolute path to the access log (resolved from the install directory).

### Logrotate configuration written:

```conf
/opt/pangolin/config/traefik/logs/access.log {
    daily
    rotate 7
    compress
    delaycompress
    missingok
    notifempty
    copytruncate
}
```
> **Note:** `copytruncate` is the key directive. It copies the log file and then truncates the original in place.  
> This allows Traefik to continue writing to the same open file descriptor without needing a restart or SIGHUP signal.

If the installer is **not running as root**, it skips writing the file and instead prints the full configuration to stdout (with the actual resolved path), allowing the user to set it up manually.

## Testing

The generated config was validated directly with `logrotate`:

```bash
# Check that the config parses cleanly
logrotate --debug /etc/logrotate.d/pangolin-traefik

# Force rotation (first time)
logrotate --force --state /tmp/test.state /etc/logrotate.d/pangolin-traefik

# Force rotation again (second time)
logrotate --force --state /tmp/test.state /etc/logrotate.d/pangolin-traefik
```
### Observed behavior:

- access.log is truncated in place after each rotation (Traefik’s file handle remains valid)
- Most recent rotated file stays uncompressed for easy inspection (delaycompress)
- Older files are compressed to .gz
- After 7 rotations, the oldest file is automatically deleted

No changes were made to the default (non-CrowdSec) installation path as suggested by @oschwartz10612.

PS : Can someone please go through [this comment](https://github.com/fosrl/pangolin/issues/2644#issuecomment-4275201183) and verify if a follow up PR like this is required where we are dropping the unused fields from crowdsec installation?

### CODE REVIEW

**Comment by AstralDestiny** [comment]
```yml
accessLog:
  filePath: "/logs/traefik/access.log"
  fields:
    headers:
      names:
        User-Agent: keep
```
For me, honestly don't even need User-Agent as I mostly have whitelists contained against traefik's own routers.

But my logs go back 2+ years and only sit with 185MB. What is the default access log look like for auto installs?

**Comment by sidd190** [comment]
> For me, honestly don't even need User-Agent as I mostly have whitelists contained against traefik's own routers.
> 
> But my logs go back 2+ years and only sit with 185MB. What is the default access log look like for auto installs?

Ahh, to be honest, I'm still learning what everything is. First time contributor here. So I can't exactly be sure if these additional fields are actually being used much, which is why I flagged it for review to kind of give a signal on what can we drop and what not on a default install settings with crowdsec, and maybe that can be addressed with a seperate PR from this.

I'll try and take a look at the default access log though. Hope you understand, sorry.

**Comment by AstralDestiny** [comment]
No worries. 🙂

Also responding from discord right now. One of the support but haven't checked what the default install recently ships with.

**Comment by sidd190** [comment]
> No worries. 🙂
> 
> Also responding from discord right now. One of the support but haven't checked what the default install recently ships with.

Ohh coool. I was thinking of putting an introduction on Discord right after getting this merged.

Umm soo, Should we wait for a response from someone else then? :) 
(I think this PR might be kinda complete in itself for adding logrotate and stop the major problem though, and then the fields for optimizations and root cause of it. Maybe you can share your installation settings template if that's okay and we can compare with default a bit too)

**Comment by AstralDestiny** [comment]
I can't touch the pr stuff so will have to wait for the others. :), Made a bot that lets me respond from discord and see everything from a glance.

**Comment by sidd190** [comment]
> I can't touch the pr stuff so will have to wait for the others. :), Made a bot that lets me respond from discord and see everything from a glance.

Got itt, thanks! (The bot sounds cool! :) )

**Comment by AstralDestiny** [comment]
Not sure if I fixed this to upload though.

image

Nope got to fix uploading then

File: install/crowdsec.go [hunk 1]
```diff
@@ -208,3 +211,80 @@ func CheckAndAddCrowdsecDependency(composePath string) error {
...
 }
+
+// setupTraefikLogRotate writes a logrotate config for the Traefik access log
+// that CrowdSec depends on. This is only needed when CrowdSec is installed
+// because the default Pangolin install does not enable Traefik access logs.
+//
+// copytruncate is used so Traefik does not need to be restarted or sent a
+// signal after rotation — it keeps writing to the same file descriptor while
+// the rotated copy is made and the original is truncated in place.
+func setupTraefikLogRotate() {
```
Comment (LaurenceJJones) [inline install/crowdsec.go]: Since we now default to `/opt/pangolin` or a custom directory if the user overrides you might need to pass the directory as an argument here now without relying on `abs(".")` since if reran to install crowdsec we might not `cwd` to it.

_edit_: my bad we do `chdir`

https://github.com/fosrl/pangolin/blob/0ac97ecd5e3eb0b3a1f950ba1b90533881ed8312/install/main.go#L94-L98

but feel free to just pass the `installDir` since we dont need to resolve it twice 🤷🏻

Comment (sidd190) [reply install/crowdsec.go]: Ahh okay, so I just passed installDir in the function. Is it okay now?

**Comment by sidd190** [comment]
@oschwartz10612 Can you please take a look at this whenever available?

**Review by oschwartz10612 — APPROVED** [review]
LGTM

**Comment by oschwartz10612** [comment]
Thanks!

**Comment by sidd190** [comment]
> Thanks!

Awesome! Thanks for the merge! There was a follow-up documentation PR for this too.

DOCS PR -> https://github.com/fosrl/docs-v2/pull/98

**Comment by oschwartz10612** [comment]
Thanks for the reminder! Merged into dev which can out out with the release
