### PR TITLE
fix: Display actual values for WireGuard site credentials

### LINKED ISSUE #2341: Basic Wireguard Site results in inconsistent interface address
### Describe the Bug

When creating a basic Wireguard site, the Wireguard Information shows an interface IP address, but then when you go back to the site, and look at the credentials, it shows a different IP address. 

Create a site:
Image

View the site:
Image

The [interface] IP addresses are different.

### Environment

- OS Type & Version: Ubuntu 24.04.3 LTS
- Pangolin Version: 1.15.0
- Gerbil Version: Latest
- Traefik Version: 3.6.7  
- Newt Version: 1.9.0

### To Reproduce

Create a Basic Wireguard site, take note of the configuration, then go edit the site and click the Credentials tab. The IP address listed under [interface] is different from the originally displayed IP address.

### Expected Behavior

The credentials should show the actual interface address.

### PR DESCRIPTION
**Pull request by Fredkiss3**
## Community Contribution License Agreement
By creating this pull request, I grant the project maintainers an unlimited,
perpetual license to use, modify, and redistribute these contributions under any terms they
choose, including both the AGPLv3 and the Fossorial Commercial license terms. I
represent that I have the right to grant this license for all contributed content.

## Summary

**Changes**:
- Show the actual values from the DB in wireguard site credentials
- Also made it so that the public key in wireguard site credentials is obfuscated 
- Bug fix: When regenerating credentials for sites using wireguard, the public key shown always `abc123` instead the actual generated public key

fixes #2341  

## Screenshots

| Name                    | Screenshots |
| :----------------: | :-----------: |
| Obfuscated wireguard credentials | Screenshot 2026-03-12 at 23 40 09 |
| Obfuscated wireguard credentials (in DB) | Screenshot 2026-03-12 at 23 40 29 |
| Regenerated public key before  |  Screenshot 2026-03-12 at 23 46 30 |
| Regenerated public key after | Screenshot 2026-03-12 at 23 46 51 |

### CODE REVIEW

**Comment by miloschwartz** [comment]
Thanks @Fredkiss3!

File: src/app/[orgId]/settings/sites/[niceId]/credentials/page.tsx [hunk 1]
```diff
@@ -100,15 +101,17 @@ export default function CredentialsPage() {
...
+                >(`/org/${orgId}/pick-site-defaults`);
                 if (res && res.status === 200) {
                     const data = res.data.data;
                     setSiteDefaults(data);
 
                     // generate config with the fetched data
                     generatedWgConfig = generateWireGuardConfig(
                         generatedKeypair.privateKey,
-                        data.publicKey,
+                        generatedKeypair.publicKey,
```
Comment (DanielAdolfsson) [inline src/app/[orgId]/settings/sites/[niceId]/credentials/page.tsx:114]: This is not what we want to display in the [Peer] PublicKey field.
